### ISSUE TITLE
ORM is not loading the correct localised Asset

### ISSUE THREAD

**Issue by davetao** [contentful/vault#107]
Hi.

I have come across a bug where if I have a localised Asset field, it will not load the correct Asset file, it will load the asset for the default locale.

The localised text fields are being loaded correctly, just the wrong asset is being loaded.

**Comment by davetao** [comment]
Hi tom,

Just to provide further information, we have created a content type with an asset field that can be localised. We updated the content models and found that the vault system is loading the incorrect asset based off the locale we have provided.

If there is a problem with the library and its not a quick fix, we have to make some big changes to our model and need to make a decision very quickly.

Do you have any idea as to what might be happening in this scenario?

**Comment by grncdr** [comment]
Hi @davetao, just wondering if you could clarify something for me. When you said:

> we have created a content type with an asset field that can be localised

Does that mean that the field definition in the content type itself has `"localize": true`? Or that you've localized the fields within the asset? In any case, it appears that Vault performs all queries in the same locale right now, which may not be the correct behaviour depending on where the localization is done.

**Comment by davetao** [comment]
Hi @grncdr 

I can confirm that the field definition in the content type has ``"localize": true``

```
{
  "name": "Audio Visual Content",
  "description": "Used for Audio/Audio Slideshow/Video",
  "displayField": "titleInternal",
  "fields": [
    {
      "name": "Title",
      "id": "title",
      "type": "Symbol",
      "localized": true,
      "validations": []
    },
    {
      "name": "Title (internal)",
      "id": "titleInternal",
      "type": "Symbol",
      "validations": []
    },
    {
      "name": "Audio Visual Media",
      "id": "audioVisualMedia",
      "type": "Link",
      "linkType": "Asset",
      "validations": [],
      "localized": true
    },
    {
      "name": "Timed images",
      "id": "timedImages",
      "type": "Array",
      "items": {
        "type": "Link",
        "linkType": "Entry",
        "validations": [
          {
            "linkContentType": [
              "xxx"
            ]
          }
        ]
      },
      "validations": [],
      "localized": true
    },
    {
      "name": "Subtitles file",
      "id": "subtitlesFile",
      "type": "Link",
      "linkType": "Asset",
      "localized": true,
      "validations": []
    }
  ]
}
```

**Comment by grncdr** [comment]
thanks @davetao, would it also be possible for you to include the JSON of one of the entries where the localized links are not being handled correctly? (Feel free to send it to support@contentful.com if there's any sensitive data involved)

**Comment by davetao** [comment]
Hi,

I have uploaded it to https://www.dropbox.com/s/b082x9qcis7e0vn/contentful.zip

We have an object with a primaryContent containing links to Assets

What we have found is that it is loading the incorrect asset at times.

**Comment by davetao** [comment]
So we were looking into the source code for Vault trying to figure it out we found that even with request for a specific locale, it was caching/loading the assets for all locales and resolving the first object.

Should the vault system be doing this even though we are asking for a specific locale?

**Comment by grncdr** [comment]
It's normal for vault to retrieve all locales, but it should only cache those that are configured in your [@Space annotation](https://github.com/contentful/vault#spaces). (It retrieves all locales because the Sync API it's based on always returns all locales).

> Should the vault system be doing this even though we are asking for a specific locale?

From your screenshot I can see the call to [`first()`](https://github.com/contentful/vault/blob/master/core/src/main/java/com/contentful/vault/FetchQuery.java#L52) without a locale specified. This causes vault to [use the default locale for the space](https://github.com/contentful/vault/blob/master/core/src/main/java/com/contentful/vault/FetchQuery.java#L28), which appears to be `"en"` in this case.

Could you confirm if `"en"` is the default locale for the space? and whether `"128 letter to an egyptologist primary ja"` is the value of `file.title.en` in the asset document? If both of those are the case then I _think_ Vault is doing the right thing.

However, it may still be the case that it's resolving the entirely wrong resource somewhere in `resolveLinksForField` since the field itself is localized.

**Comment by davetao** [comment]
Hi,
"en" is indeed the default locale. "128 letter to an egyptologist primary ja" is the name of the asset sitting under the "ja" locale

You are right to say that I didnt specify a locale, which i fixed, but its still producing the wrong result unfortunately.

We believe that this problem can be reproduced with a basic test that has multiple locales.

**Comment by davetao** [comment]
After doing more tracing. Could it be that the "links" table for each locale has more than one locale being stored in it?

The following link asks for links for the asset

https://github.com/contentful/vault/blob/5f9b46f5506683a86a4c352f4192de1a839c6e2c/core/src/main/java/com/contentful/vault/LinkResolver.java#L62

using the following query
```SELECT l.child, null FROM `links$es` l WHERE l.parent = "5MC1AWSJEsyQCUuaW8csAk" AND l.is_asset = 1 AND l.field = "audioVisualMedia" ORDER BY l.position```

but it is returning 10 results, where it should be just the one for that locale.

This would mean that the database is being populated incorrectly during sync

<img width="1069" alt="screen shot 2015-11-19 at 12 20 37 pm" src="https://cloud.githubusercontent.com/assets/4438069/11270566/fd123f24-8eb7-11e5-8ca9-6b1a2541cf51.png">

**Comment by grncdr** [comment]
Good find! I assume the issue persists after clearing the database and doing a fresh sync?

**Comment by davetao** [comment]
Yes that is correct.

**Comment by davetao** [comment]
It comes up with 10 entries because we have 10 locales

**Comment by grncdr** [comment]
Got it, thanks for digging in here :heart: we will try and reproduce/resolve the issue ASAP.

**Comment by davetao** [comment]
Thanks for looking into the issue @tomxor @grncdr . much appreciated

**Comment by tomxor** [comment]
thanks for the bug report @davetao! not sure how this didn't show up earlier. I'll add some fixes to the PR and merge this soon.

**Comment by davetao** [comment]
Totally understand how it came about. I appreciate that you changed the core functionality to accept multiple locales to make this library work.

I can verify your work once its been merged. Would be amazing to see it before we do some scheduled language testing tomorrow if that is at all possible.

**Comment by tomxor** [comment]
Working on it now, should take just a few minutes.

**Comment by tomxor** [comment]
@davetao this has been merged to master, a snapshot should be available on Sonatype within the next 10 minutes or so. Apparently there was very little test coverage around this area, so any feedback you can provide would be greatly appreciated. I'd rather leave the issue open for now, until you report back. Once you do (assuming all goes well) I'll roll out the next release to Maven. Thanks a lot!

**Comment by davetao** [comment]
Thanks. ill have a look in a few minutes. Cheers.

**Comment by davetao** [comment]
How do i get to this snapshot? or have you made a release like the other builds?

**Comment by tomxor** [comment]
Follow up: 3d672ba50e9e556615d2f251b6138f6b2a97d63f

**Comment by tomxor** [comment]
@davetao I'll roll out 0.9.13 in a few minutes, so there's no need for the snapshot.

**Comment by tomxor** [comment]
Just pushed 0.9.13 to Sonatype, should be available via Central within 10-15 minutes. Will re-open in case there are any issues.

**Comment by davetao** [comment]
The correct localised assets are now appearing.

There is a problem though, with the non localised assets. we have a set of images that we use that normally dont need to be localised. They currently arent loading

**Comment by davetao** [comment]
In fact i think the system is not loading non localised links anymore. Would you be able to have a look at that?

**Comment by tomxor** [comment]
Are you referring to a single link, or array of links?

**Comment by davetao** [comment]
From what I can see, it would be the array of links

**Comment by tomxor** [comment]
I am unable to reproduce this issue.. there are also some tests covering this functionallity, https://github.com/contentful/vault/blob/master/tests-integration/src/test/java/com/contentful/vaultintegration/LinksTest.java#L35-L84 -- can you provide more details?

**Comment by davetao** [comment]
I have had a look at your test, so i can confirm that if you do not specify a locale, it will load up the content just fine.

If you ask for a specific locale, it will then miss the non localised linked objects.

I am sure you can replicate the bugs if you ask for a specific locale

**Comment by willjrobinson** [comment]
Hi Tom - any update on this issue?

**Comment by tomxor** [comment]
Still unable to reproduce. Non-localized links/arrays of links seem to work fine. Can someone provide a failing test-case?

**Comment by tomxor** [comment]
I see it now, will look soon.

**Comment by davetao** [comment]
Thank you for looking into it. I shall use the 0.9.14-SNAPSHOT build to check the results.

**Comment by davetao** [comment]
Hi @tomxor ,
So I am using the following gradle command to grab the snapshots. 
```
    apt 'com.contentful.vault:compiler:0.9.14-SNAPSHOT'
    compile 'com.contentful.vault:core:0.9.14-SNAPSHOT'
```
I cant seem to be getting the latest version. Apologies as I am not quite sure how to proceed from here.

**Comment by tomxor** [comment]
@davetao @willjrobinson v0.9.14 has been released, should be available on central in a few minutes.

**Comment by davetao** [comment]
Thank you. testing it right away.

**Comment by davetao** [comment]
We will continue to test but for the most part it looks like the bugs raised has been fixed.
Thank you Tom

**Comment by tomxor** [comment]
Awesome! and no problem :)
